# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gbTzuGm8iZscVJPyH-YGkiptP38C2kiw
"""

pip install pyttsx3 pdfplumber PyPDF2

"""#Description: This program converts a pdf to a audio book."""

import pyttsx3
import pdfplumber
import PyPDF2

file = './argument.pdf'

#Creating a PDF File Object
pdfFileObj = open(file, 'rb')

# creating a pdf reader object
pdfReader = PyPDF2.PdfFileReader(pdfFileObj)

#Get the number of pages
pages = pdfReader.numPages

#Create a pdfplumber object and loop through the pages
with pdfplumber.open(file) as pdf:
 #Loop through the number of pages
    for i in range(0, pages): 
      page = pdf.pages[i]
      text = page.extract_text()
      print(text)
      speaker = pyttsx3.init()
      speaker.say(text)
      speaker.runAndWait()